<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Copyright>Copyright (C) 2016-2026 KKTS Ltd.</Copyright>
    <Version>3.0.1</Version>
    <Authors>Linh Le</Authors>
    <Product>Dynamic Expression</Product>
    <Company>KKTS Ltd.</Company>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/linhnle/Kkts.Expressions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/linhnle/Kkts.Expressions.git</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Build dynamic LINQ filters from strings or structured objects, with sorting and pagination for .NET applications.</Description>
    <PackageTags>expression;lambda-expression;dynamic-expression;string-expression;query;string-query;jira-filter;linq;expression-tree;dynamic-filter;predicate-builder;query-builder;filtering;sorting;pagination</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
		<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
